name: classifie

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate Documentation
        run: |
          # Dowloading the swagger client
          wget https://github.com/swaggo/swag/releases/download/v1.7.0/swag_1.7.0_Linux_x86_64.tar.gz
          tar -xvf swag_1.7.0_Linux_x86_64.tar.gz
          ./swag init -g pkg/apis/api_controller.go --output docs
          rm swag
          rm swag_1.7.0_Linux_x86_64.tar.gz

      - name: build and deploy
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_USERNAME }}evolza/classifie
          tags: latest
          registry: docker.io
          username: ${{ secrets.EVOCODE_DOCKER_USERNAME }}
          password: ${{ secrets.EVOCODE_DOCKER_ACCESSCODE }}

